/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.humbird.soa.ipc.avro.vo;

@SuppressWarnings("all")
/** This is a message. */
@org.apache.avro.specific.AvroGenerated
public interface MessageProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"MessageProtocol\",\"namespace\":\"org.humbird.soa.db.rpc.avro.vo\",\"doc\":\"This is a message.\",\"name\":\"Message\",\"types\":[{\"type\":\"record\",\"name\":\"Message\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"int\"},{\"name\":\"price\",\"type\":\"double\"},{\"name\":\"valid\",\"type\":\"boolean\"},{\"name\":\"content\",\"type\":\"bytes\"},{\"name\":\"tags\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}],\"messages\":{\"sendMessage\":{\"doc\":\"test\",\"request\":[{\"name\":\"message\",\"type\":\"Message\"}],\"response\":\"Message\"}}}");
  /** test */
  Message sendMessage(Message message) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** This is a message. */
  public interface Callback extends MessageProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = MessageProtocol.PROTOCOL;
    /** test */
    void sendMessage(Message message, org.apache.avro.ipc.Callback<Message> callback) throws java.io.IOException;
  }
}