/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.humbird.soa.db.rpc.avro.vo;

@SuppressWarnings("all")
/** Protocol Greetings */
@org.apache.avro.specific.AvroGenerated
public interface HelloWorld {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"HelloWorld\",\"namespace\":\"org.humbird.soa.db.rpc.avro.vo\",\"doc\":\"Protocol Greetings\",\"types\":[{\"type\":\"record\",\"name\":\"Greeting\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"}]},{\"type\":\"error\",\"name\":\"Curse\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"}]}],\"messages\":{\"hello\":{\"doc\":\"Say hello.\",\"request\":[{\"name\":\"greeting\",\"type\":\"Greeting\"}],\"response\":\"Greeting\",\"errors\":[\"Curse\"]}}}");
  /** Say hello. */
  org.humbird.soa.db.rpc.avro.vo.Greeting hello(org.humbird.soa.db.rpc.avro.vo.Greeting greeting) throws org.apache.avro.AvroRemoteException, org.humbird.soa.db.rpc.avro.vo.Curse;

  @SuppressWarnings("all")
  /** Protocol Greetings */
  public interface Callback extends HelloWorld {
    public static final org.apache.avro.Protocol PROTOCOL = org.humbird.soa.db.rpc.avro.vo.HelloWorld.PROTOCOL;
    /** Say hello. */
    void hello(org.humbird.soa.db.rpc.avro.vo.Greeting greeting, org.apache.avro.ipc.Callback<org.humbird.soa.db.rpc.avro.vo.Greeting> callback) throws java.io.IOException;
  }
}